### ISSUE TITLE
Error undefinied var kubernetes_ip_address

### ISSUE THREAD

**Issue by andreissf** [garutilorenzo/ansible-role-linux-kubernetes#2]
I am trying to deploy a cluster into a server but its throwing the error that the kubernetes_ip_address ir undefinied. I didn't see any instruction regarding this in documentation.
any idea?

Thanks

**Comment by garutilorenzo** [comment]
Hi @andreissf, 

have you setup *kubernetes_subnet* variable?
What is your k8s subnet? How many interfaces have your servers?

**Comment by andreissf** [comment]
Hi @garutilorenzo ,
thanks reply.
Yes, I had. 
kubernetes_subnet: 10.244.0.0/16

**Comment by andreissf** [comment]
here more details about my error:
TASK [ansible-role-linux-kubernetes : set_fact] *******************************************************************************************************************************
fatal: [masternode]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'kubernetes_ip_address'\n\nThe error appears to be in '/.../.ansible/roles/ansible-role-linux-kubernetes/tasks/join_cluster.yml': line 8, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- set_fact:\n  ^ here\n"}

**Comment by andreissf** [comment]
I am trying to deploy it In Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-128-generic x86_64).

Regards.

**Comment by garutilorenzo** [comment]
Hi @andreissf,
 
I think I've found the problem, please  try again add get the update from the repo.
