### ISSUE TITLE
Role is very nice, but I get this error: has no attribute 'kubernetes_ip_address'\

### ISSUE THREAD

**Issue by yavasura** [garutilorenzo/ansible-role-linux-kubernetes#3]
TASK [ansible-role-linux-kubernetes : Check if /var/lib/kubelet directory exist] **************************************************************************************
ok: [k8s_master_1]

TASK [ansible-role-linux-kubernetes : set_fact] ***********************************************************************************************************************
[DEPRECATION WARNING]: Use 'ansible.utils.ipaddr' module instead. This feature will be removed from ansible.netcommon in a release after 2024-01-01. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
skipping: [k8s_master_1] => (item=192.168.122.190) 

TASK [ansible-role-linux-kubernetes : set_fact] ***********************************************************************************************************************
fatal: [k8s_master_1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'kubernetes_ip_address'\n\nThe error appears to be in '/root/.ansible/roles/ansible-role-linux-kubernetes/tasks/join_cluster.yml': line 13, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- set_fact:\n  ^ here\n"}

PLAY RECAP ************************************************************************************************************************************************************
k8s_master_1               : ok=35   changed=7    unreachable=0    failed=1    skipped=30   rescued=0    ignored=1

**Comment by garutilorenzo** [comment]
@Norkevicius can you please share your vars.yaml file and your network configuration *ifconfig* or *ip addr list*?

**Comment by garutilorenzo** [comment]
No feedback received
