### ISSUE TITLE
"The task includes an option with an undefined variable. 'kubernetes_ip_address

### ISSUE THREAD

**Issue by ViktorRush** [garutilorenzo/ansible-role-linux-kubernetes#6]
Hey,
I have ran into the same issue as others before me.
![Screenshot from 2022-12-14 13-08-35](https://user-images.githubusercontent.com/120171874/207593800-84a0a974-fe7c-4561-8aa7-0796255fb73b.png)
![Screenshot from 2022-12-14 13-12-02](https://user-images.githubusercontent.com/120171874/207593808-14b041ef-3f29-4c42-a3e2-fc332c766ae1.png)
![Screenshot from 2022-12-14 13-17-39](https://user-images.githubusercontent.com/120171874/207593812-415e821a-5b66-4de7-9e01-36de2fb1cad7.png)

**Comment by garutilorenzo** [comment]
Hi @ViktorRush,

you have to set the correct value for kubernetes subnet.
Based on your ifconfig I think the correct value is 172.21.23.16/28
